require('pathlra-aliaser')();

const coreLoader = require('@loader-core_bootstrap');
const botClient = global.client;
const { handleInteraction } = require('@interactionProcessor-core_interactions');
const { getErrorType } = require('@interactionErrors-core_interactions');

// Initialize rate limit map and attach auto-cleanup interval
if (!global.interactionRateLimits) {
    global.interactionRateLimits = new Map();
}
setInterval(() => {
    if (!global.interactionRateLimits || !global.interactionRateLimits.size) return;
    const now = Date.now();
    const threshold = 2000; // 2s TTL provides safe margin for duplicate detection
    for (const [key, ts] of global.interactionRateLimits.entries()) {
        if (now - ts > threshold) global.interactionRateLimits.delete(key);
    }
}, 5000);

botClient.on('interactionCreate', async (interaction) => {
    try {
        // Filter to only process supported interaction types
        if (!interaction.isCommand() && !interaction.isButton() && !interaction.isStringSelectMenu() && !interaction.isModalSubmit()) {
            return;
        }
        // Ignore interactions generated by the bot itself to prevent loops
        if (interaction.user.id === botClient.user.id) {
            return;
        }
        // Generate unique ID for rate limiting duplicate rapid clicks
        const interactionId = `${interaction.guildId}-${interaction.user.id}-${interaction.id}`;
        // Enforce 500ms minimum interval between identical interactions from same user
        if (global.interactionRateLimits && global.interactionRateLimits.has(interactionId)) {
            const lastTime = global.interactionRateLimits.get(interactionId);
            const now = Date.now();
            if (now - lastTime < 500) {
                coreLoader.logger.debug(`Ignored Fast Duplicate Interaction ${interactionId}`);
                return;
            }
        }
        global.interactionRateLimits.set(interactionId, Date.now());
        // Route interaction to centralized processor
        await handleInteraction(interaction);
    } catch (criticalError) {
        // Handle completely unexpected errors that bypass normal error handling
        coreLoader.logger.critical('Unexpected Error In Interaction Handler');
        try {
            // Attempt to notify user of critical system issue if interaction is still valid
            if (interaction && !interaction.replied && !interaction.deferred) {
                const errorType = getErrorType(criticalError);
                if (errorType !== 'INTERACTION_EXPIRED') {
                    await interaction.deferUpdate();
                    await interaction.editReply({
                        content: 'حدث خطأ حرج في النظام جاري المحاولة لاستعادة الخدمة',
                        flags: coreLoader.MessageFlags.Ephemeral,
                    });
                    // Auto-recovery message after brief delay
                    setTimeout(async () => {
                        try {
                            await interaction.editReply({
                                content: 'تم استعادة النظام بنجاح يرجى المحاولة مرة اخرى',
                                flags: coreLoader.MessageFlags.Ephemeral,
                            });
                        } catch (recoveryError) {
                            coreLoader.logger.debug('Failed To Recover Error Message');
                        }
                    }, 2000);
                }
            }
        } catch (replyError) {
            coreLoader.logger.error('Failed To Send Critical Error Message To User');
        }
    }
});

// Load remaining global modules after interaction handler is registered
require('@globalAll');
